### ISSUE TITLE
サンプル/アプリ/スケッチの画像が時計のものになっている

### ISSUE THREAD

**Issue by oyakodon** [Siv3D/siv3d.docs#2]
English・日本語両方で
サンプル/アプリ中のスケッチのgif画像が
時計のgif画像になっていました.

https://siv3d.github.io/ja-jp/sample/app/#_2
https://github.com/Siv3D/siv3d.docs/blob/master/docs/ja-jp/sample/app.md

![image](https://user-images.githubusercontent.com/16263307/71093887-61343a80-21ed-11ea-89ca-2c7e9eb6af79.png)

**Comment by Reputeless** [comment]
Fixed. Thanks!
