### ISSUE TITLE
[tutorial] 5.5アイコンを描画するのコードがハイライトされていない

### ISSUE THREAD

**Issue by yumetodo** [Siv3D/siv3d.docs#59]
https://siv3d.github.io/ja-jp/tutorial/texture/#55
![image](https://user-images.githubusercontent.com/10869046/104160437-7e5d2c00-5434-11eb-93ea-96fb95a3fac5.png)

markdownに問題は見られないのでからの変換に失敗していると思います。

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
"```" の直後の `C++` の付け忘れでした。
C++ を付けないと C++ のコードとしてハイライトされません。
修正します。

**Comment by Reputeless** [comment]
#58 で解決済みなのが Web サイトに反映されていなかったようです。
すみません。まもなく解決します。
