### ISSUE TITLE
英語版(まだ日本語で書かれている)に日本語版と同様の誤植がある場合について

### ISSUE THREAD

**Issue by ROCKTAKEY** [Siv3D/siv3d.docs#62]
先日マージしていただいたPR #61 について、全く同じ誤植が(まだ日本語のままの)英語版でも見られることに気が付きました。
https://github.com/Siv3D/siv3d.docs/blob/b4d0494902712b9e8598c6dc21beb700038dfb16/docs/tutorial/data-structures.md#%E8%A6%81%E7%B4%A0%E6%95%B0%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%9F%E5%88%9D%E6%9C%9F%E5%8C%96-1
英語版に関して、もう一度PRを出すべきでしょうか。また、今後PRを出す際、両方を含めて出すべきでしょうか。現状の英語版の立ち位置をお教えいただけると助かります。

**Comment by Reputeless** [comment]
どちらでも OK です。両方だと助かります。
現在のページは v0.6 で完全に置き換え予定なので、最近メンテの機運が落ちています 🙄

**Comment by ROCKTAKEY** [comment]
了解です！ありがとうございます！
