### ISSUE TITLE
クラス一覧の typo

### ISSUE THREAD

**Issue by Raclamusi** [Siv3D/siv3d.docs#69]
「クラス一覧」のページの誤植を2つ見つけたので、報告します。

- detail: → detail::
https://github.com/Siv3D/siv3d.github.io/blob/6de7179f2af489073e0a169eb1758c1c7146ac34/api/classes/index.html#L2424

- Serialize → Serializer
https://github.com/Siv3D/siv3d.github.io/blob/6de7179f2af489073e0a169eb1758c1c7146ac34/api/classes/index.html#L3184

**Comment by Reputeless** [comment]
Fixed. Thanks!
