### ISSUE TITLE
「コーディングスタイル」の誤植

### ISSUE THREAD

**Issue by eightgamedev** [Siv3D/siv3d.docs#76]
「コーディングスタイル」ページについて日本語版と英語版それぞれに1つずつの誤植がありますので報告させていただきます。

privete -> private

https://github.com/Siv3D/siv3d.docs/blob/61fd2575d1892d945e0d8723897904def5959e51/ja-jp/docs/develop/coding-style.md?plain=1#L70

https://github.com/Siv3D/siv3d.docs/blob/61fd2575d1892d945e0d8723897904def5959e51/en-us/docs/develop/coding-style.md?plain=1#L70

**Comment by Reputeless** [comment]
ご報告ありがとうございます。
GitHub 上でリポジトリをフォークし、数クリックで修正の pull request を作成できますが、ご自分でされない場合は私が修正しておきます。
